# SPDX-License-Identifier: AGPL-3.0-or-later
"""Canonical Canvas Pilot route normalization and delivery classification.

This module is deliberately free of Canvas network calls.  Both the scanner
and later execution code can use the same deterministic mapping without
falling back to the legacy in-process dispatcher.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Mapping

from .ac_eng_router import route_ac_eng_assignment


class RouteConfigError(ValueError):
    """The local route configuration cannot be interpreted safely."""


_CANONICAL_SKILL_RE = re.compile(r"^canvas-[a-z0-9]+(?:-[a-z0-9]+)*$")

# The values are Codex skill names under .agents/skills/.  Legacy aliases are
# accepted for existing local courses.yaml files, but are never emitted by a
# product scan.
SKILL_ALIASES: dict[str, str] = {
    "code_py": "canvas-ics33",
    "ics33": "canvas-ics33",
    "quiz": "canvas-inside",
    "inside": "canvas-inside",
    "zybooks": "canvas-zybooks",
    "essay": "canvas-essay",
    "reading_annotation": "canvas-reading-annotation",
    "reading-annotation": "canvas-reading-annotation",
    "generic": "canvas-generic",
    "mixed_unsupported": "canvas-skip",
    "manual_skip": "canvas-skip",
    "skip": "canvas-skip",
}

WRITING_ROUTE_ALIASES = {
    "ac_english",
    "writing",
    "canvas-writing",
}

SUPPORTED_DELIVERY_TYPES = {
    "online_upload",
    "online_text_entry",
    "online_url",
    "media_recording",
    "student_annotation",
    "online_quiz",
}


@dataclass(frozen=True)
class RouteDecision:
    """Final scan-time route decision for one assignment."""

    skill: str
    configured_skill: str
    reason_code: str | None = None


def _normalize_skill_name(value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise RouteConfigError("route skill must be a non-empty string")
    return value.strip().lower().replace(" ", "-")


def canonicalize_skill(value: Any, assignment: Mapping[str, Any]) -> RouteDecision:
    """Resolve one configured skill, including the deterministic writing split.

    Unknown bare aliases fail closed to ``canvas-skip``.  Syntactically valid
    ``canvas-*`` names are retained so a public-safe skill generated by
    canvas-bootstrap can participate without editing this registry.
    """

    configured = _normalize_skill_name(value)
    if configured in WRITING_ROUTE_ALIASES:
        writing_kind = route_ac_eng_assignment(dict(assignment))
        skill = (
            "canvas-essay"
            if writing_kind == "essay"
            else "canvas-reading-annotation"
        )
        return RouteDecision(skill=skill, configured_skill=configured)

    canonical = SKILL_ALIASES.get(configured, configured)
    if _CANONICAL_SKILL_RE.fullmatch(canonical):
        return RouteDecision(skill=canonical, configured_skill=configured)
    return RouteDecision(
        skill="canvas-skip",
        configured_skill=configured,
        reason_code="unknown_route_skill",
    )


def matches_override(assignment: Mapping[str, Any], match_spec: Mapping[str, Any]) -> bool:
    """Return whether every override field matches the assignment."""

    for key, expected in match_spec.items():
        actual = assignment.get(key)
        if isinstance(expected, list):
            if not isinstance(actual, (list, tuple)):
                return False
            if set(actual) != set(expected):
                return False
        elif actual != expected:
            return False
    return True


def normalize_route(course_id: str | int, raw: Any) -> dict[str, Any]:
    """Normalize an object route or documented shorthand string.

    ``123: canvas-ics33`` is accepted as a shorthand for an object route.  A
    generic local-only display name is used when the shorthand provides none.
    """

    cid = str(course_id)
    if isinstance(raw, str):
        return {
            "name": f"Course {cid}",
            "skill": _normalize_skill_name(raw),
            "overrides": [],
        }
    if not isinstance(raw, Mapping):
        raise RouteConfigError(
            f"route {cid!r} must be a skill string or mapping, got {type(raw).__name__}"
        )

    skill = _normalize_skill_name(raw.get("skill"))
    name = raw.get("name")
    if not isinstance(name, str) or not name.strip():
        name = f"Course {cid}"

    overrides = raw.get("overrides") or []
    if not isinstance(overrides, list):
        raise RouteConfigError(f"route {cid!r} overrides must be a list")
    clean_overrides: list[dict[str, Any]] = []
    for index, override in enumerate(overrides):
        if not isinstance(override, Mapping):
            raise RouteConfigError(
                f"route {cid!r} override {index} must be a mapping"
            )
        match = override.get("match") or {}
        if not isinstance(match, Mapping):
            raise RouteConfigError(
                f"route {cid!r} override {index} match must be a mapping"
            )
        clean_overrides.append(
            {
                "match": dict(match),
                "skill": _normalize_skill_name(override.get("skill")),
            }
        )

    return {"name": name.strip(), "skill": skill, "overrides": clean_overrides}


def normalize_routes(config: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    raw_routes = config.get("routes")
    if raw_routes is None:
        return {}
    if not isinstance(raw_routes, Mapping):
        raise RouteConfigError("courses.yaml routes must be a mapping")
    return {
        str(course_id): normalize_route(course_id, raw)
        for course_id, raw in raw_routes.items()
    }


def configured_skill_for(route: Mapping[str, Any], assignment: Mapping[str, Any]) -> str:
    for override in route.get("overrides") or []:
        if matches_override(assignment, override.get("match") or {}):
            return _normalize_skill_name(override.get("skill"))
    return _normalize_skill_name(route.get("skill"))


def apply_delivery_policy(
    decision: RouteDecision,
    assignment: Mapping[str, Any],
) -> RouteDecision:
    """Fail closed for delivery modes the Codex product cannot safely handle."""

    raw_types = assignment.get("submission_types")
    if not isinstance(raw_types, (list, tuple)) or not raw_types:
        return RouteDecision(
            "canvas-skip", decision.configured_skill, "missing_submission_type"
        )
    submission_types = {
        str(value).strip().lower() for value in raw_types if str(value).strip()
    }

    if "on_paper" in submission_types:
        return RouteDecision("canvas-skip", decision.configured_skill, "on_paper")
    if "external_tool" in submission_types:
        return RouteDecision(
            "canvas-skip", decision.configured_skill, "external_tool_unsupported"
        )
    if submission_types <= {"none", "not_graded"}:
        return RouteDecision(
            "canvas-skip", decision.configured_skill, "no_online_submission"
        )
    if not submission_types.intersection(SUPPORTED_DELIVERY_TYPES):
        return RouteDecision(
            "canvas-skip",
            decision.configured_skill,
            "unsupported_submission_type",
        )

    if "online_quiz" in submission_types:
        if not assignment.get("quiz_id"):
            return RouteDecision(
                "canvas-skip",
                decision.configured_skill,
                "new_quiz_or_missing_classic_quiz_id",
            )
        # A Classic Quiz always goes through the one authorized quiz skill,
        # independent of a course-wide legacy default.
        return RouteDecision("canvas-inside", decision.configured_skill)

    return decision


def resolve_route(route: Mapping[str, Any], assignment: Mapping[str, Any]) -> RouteDecision:
    configured = configured_skill_for(route, assignment)
    decision = canonicalize_skill(configured, assignment)
    if decision.reason_code:
        return decision
    return apply_delivery_policy(decision, assignment)


def resolve_skill(
    route: Mapping[str, Any] | str,
    assignment: Mapping[str, Any],
) -> str:
    """Return the canonical ``canvas-*`` skill for one assignment.

    Framework callers use this compact surface to share the scanner's alias,
    override, writing-split, and delivery-safety rules.  Call
    :func:`resolve_route` when the stable skip reason is also needed.
    """

    if isinstance(route, str):
        course_id = assignment.get("course_id") or "unknown"
        route = normalize_route(course_id, route)
    return resolve_route(route, assignment).skill


def has_lockdown_browser(quiz: Mapping[str, Any]) -> bool:
    """Interpret Canvas metadata only; this does not claim plugin availability."""

    return any(
        quiz.get(field) is True
        for field in (
            "require_lockdown_browser",
            "require_lockdown_browser_for_results",
            "require_lockdown_browser_monitor",
        )
    )
